bounswe/bounswe2019group8

practice-app/backend/app.py

- Implementation of comment model in database
- HTTP POST method for comments API (create comment)
- HTTP DELETE method for comments API (delete comment)
#74 , #75

Backend - API and Database Model Implementation

---

practice-app/backend/flaskr/models.py
practice-app/backend/flaskr/trading_equipments.py

Backend prediction functions

---

practice-app/backend/flaskr/__init__.py
practice-app/backend/flaskr/config.py
practice-app/backend/flaskr/models.py
practice-app/backend/flaskr/price_api_uplink.py
practice-app/backend/flaskr/trading_equipments.py

Small fixes for the backend app.

Small fixes

---

practice-app/backend/flaskr/config.py
practice-app/backend/flaskr/db.py
practice-app/backend/tests/test_flaskr.py

add comment list and create test

---

.gitignore
backend/src/main/java/com/traders/backend/controller/AdminOperationController.java
backend/src/main/java/com/traders/backend/controller/AuthenticationController.java
backend/src/main/java/com/traders/backend/dto/LoginCredentials.java
backend/src/main/java/com/traders/backend/dto/RegisterCredentials.java

Former content type of requests using ```POST``` method was ```application/x-www-form-urlencoded```. This is changed to ```application/json```.
See #137 
Also updated .gitignore file to avoid tracking .DS_STORE files created in MAC computers.

Move POST request content type from url encoded to json

---

mobile/Mercatus/.idea/misc.xml
mobile/Mercatus/.idea/vcs.xml
mobile/Mercatus/app/src/main/res/layout/activity_guest.xml
mobile/Mercatus/app/src/main/res/layout/activity_register.xml
mobile/Mercatus/app/src/main/res/values/strings.xml

Resgiter page is partially developped.
Needs fix and improvement.
...

Merge Android

---

mobile/Mercatus/.idea/misc.xml
mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/LoginActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/TraderUserActivity.kt
mobile/Mercatus/app/src/main/res/layout/activity_trader_user.xml
mobile/Mercatus/app/src/main/res/values/strings.xml

Create user sign up pages.

---

backend/README.md
backend/pom.xml
backend/src/main/java/com/traders/backend/config/SecurityConfig.java
backend/src/main/java/com/traders/backend/controller/AdminOperationController.java
backend/src/main/java/com/traders/backend/controller/AuthenticationController.java
backend/src/main/java/com/traders/backend/controller/UserController.java
backend/src/main/java/com/traders/backend/dto/IdWrapper.java
backend/src/main/java/com/traders/backend/dto/RegisterCredentials.java
backend/src/main/java/com/traders/backend/model/User.java
backend/src/main/java/com/traders/backend/repository/UsersRepository.java
backend/src/main/java/com/traders/backend/security/JwtAuthenticationFilter.java
backend/src/main/java/com/traders/backend/security/JwtTokenProvider.java
backend/src/main/java/com/traders/backend/security/UserPrincipal.java
backend/src/main/java/com/traders/backend/service/UserDetailsServiceImpl.java
backend/src/main/java/com/traders/backend/service/UserService.java
backend/src/main/java/com/traders/backend/service/UserServiceImpl.java
backend/src/main/resources/application.properties

- Database is changed to PostGre, from Mongo.
- To have a cleaner coding pattern, repository calls are removed from controllers.
Now controllers call services, services use repositories.
- Endpoint to follow a user is created
See #139

Feature b139

---

mobile/Mercatus/app/build.gradle
mobile/Mercatus/app/src/main/res/drawable/ic_check.xml
mobile/Mercatus/app/src/main/res/layout/activity_basic_user.xml
mobile/Mercatus/app/src/main/res/layout/activity_trader_user.xml
mobile/Mercatus/app/src/main/res/values/strings.xml

Develop Register Pages for Users.

---

nova/nova/models.py
nova/nova/serializers.py
nova/nova/urls.py
nova/nova/views.py

Follow and unfollow endpoints are added to backend
See #171 
Try like the following:
POST --> localhost:8000/users/1/followings
data: {"following_pk": 2}
GET --> localhost:8000/users/1/followings
GET --> localhost:8000/users/2/followers
DELETE --> localhost:8000/users/1/followings/2
Don't forget to migrate your db.

Add follow and unfollow endpoints

---

mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/BasicUserActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/LoginActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/RegisterActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/TraderUserActivity.kt
mobile/Mercatus/app/src/main/res/layout/activity_basic_user.xml

Sign up page credentials are implemented.
...
...

Sign up page credentials are implemented.

---

mobile/Mercatus/.idea/misc.xml
mobile/Mercatus/app/build.gradle
mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/BasicUserActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/LoginActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/SaveActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/SignInRes.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/User.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UserBody.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UserRes.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ModifyActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ProfileActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/SearchActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/TraderUserActivity.kt
mobile/Mercatus/app/src/main/res/layout/activity_load.xml
mobile/Mercatus/app/src/main/res/layout/activity_modify.xml
mobile/Mercatus/app/src/main/res/layout/activity_profile.xml
mobile/Mercatus/app/src/main/res/layout/activity_search.xml
mobile/Mercatus/app/src/main/res/xml/network_security_config.xml
mobile/Mercatus/build.gradle

- User page is updated according to backend application
...
...

page transitions with backend

---

mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/BasicUserActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ProfileActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/SearchActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/TraderUserActivity.kt
mobile/Mercatus/app/src/main/res/layout/activity_guest.xml
mobile/Mercatus/app/src/main/res/layout/activity_search.xml

- Connected register pages to profile pages. When registered, login works in the background automatically
- Created a search page draft to prevent app crash when clicked on search button.
- Changed signup condition to a better one.
#181

Connect register page to profile

---

mobile/Mercatus/app/build.gradle
mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Adapters/ListViewAdapter.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/LoginActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/MainActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UserFollower.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UserNames.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UserRes.kt
mobile/Mercatus/app/src/main/res/drawable/ic_search.xml
mobile/Mercatus/app/src/main/res/layout/activity_main.xml
mobile/Mercatus/app/src/main/res/layout/lv_item.xml
mobile/Mercatus/app/src/main/res/values/strings.xml
mobile/Mercatus/build.gradle

- Created search layout and adjust to main screen.
- Connected with backend for search property.
#184

Search function basic is created.

---

mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/BasicUserActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/LoginActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/MainActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/TraderUserActivity.kt
mobile/Mercatus/app/src/main/res/anim/slide_in_left.xml
mobile/Mercatus/app/src/main/res/anim/slide_in_right.xml
mobile/Mercatus/app/src/main/res/anim/slide_out_left.xml
mobile/Mercatus/app/src/main/res/anim/slide_out_right.xml
mobile/Mercatus/app/src/main/res/values/strings.xml

Determined depreciated functions, replaced with new ones. Added transition animations.
#202

Depreciated functions are replaced and added transition animations.

---

nova/nova/models.py
nova/nova/serializers.py
nova/nova/views.py

Fixes the double hashed password problem. See the issue for more details.
#206

Fix the double hashed password problem

---

mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/FollowersActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/FollowingsActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/MainActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/SearchActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/ShowProfileActivity.kt
mobile/Mercatus/app/src/main/res/layout/activity_followers.xml
mobile/Mercatus/app/src/main/res/layout/activity_followings.xml
mobile/Mercatus/app/src/main/res/layout/activity_show_profile.xml
mobile/Mercatus/app/src/main/res/values/strings.xml

Followings and followers layout is created
#185

Followings and followers layout is created

---

nova/nova/views.py

Require email activation to login if not in debug mode.
#215

require email activation to login if not in debug mode

---

mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/LoginActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/ShowProfileActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/FollowBody.kt
mobile/Mercatus/app/src/main/res/values/colors.xml

Follow and unfollow user functionality is added. 
#220  
...

Feature m220

---

frontend/my-app/src/components/article_components/articleHolder.jsx
frontend/my-app/src/components/article_components/main_article_holder.jsx
frontend/my-app/src/components/main_pages/basicMainPage.jsx
frontend/my-app/src/components/main_pages/guestMainPage.jsx
frontend/my-app/src/components/nav_bars/traderNavbar.jsx
frontend/my-app/src/components/parity_components/graph.jsx
frontend/my-app/src/components/parity_components/parity_page.css
frontend/my-app/src/components/parity_components/parity_page.jsx

Parity pages were designed to some degree.

Parity page effort has started.

---

mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/ModifyActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/ModifyPasswordActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UpdatePassword.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UpdateUserBody.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/ProfileFragment.kt
mobile/Mercatus/app/src/main/res/layout/change_password.xml
mobile/Mercatus/app/src/main/res/layout/fragment_profile.xml

For update profile, 
1-name and surname removed from the edit profile. They will stay constant for each account.
2-Changing password functionality is added.
...
...

Changing password

---

nova/nova/models.py

Removes the content length restrictions of the article and comment models.
#256

Remove content length restrictions

---

nova/nova/libs/parse_event_data.py
nova/nova/models.py
nova/nova/other_views/events.py
nova/nova/permissions.py
nova/nova/serializers.py
nova/nova/urls.py

Implement the events API.
#255 
### Example Request and Output
Send GET to `events/2019-11-22`to get the events. Example response:
```json
[
{
"id": "396887",
"date": "2019-11-22",
"time": "01:00",
"name": "Manufacturing PMI",
"country": "Australia",
"importance": 1,
"value": "49.9"
}
]
```
Send POST to the same address to fetch the events from the 3rd party provider.

Events API

---

frontend/my-app/src/components/article_components/articleCommentCard.jsx
frontend/my-app/src/components/article_components/articleCommentHolder.css
frontend/my-app/src/components/article_components/articleCommentHolder.jsx
frontend/my-app/src/components/article_components/articleHolder.css
frontend/my-app/src/components/article_components/articleHolder.jsx
frontend/my-app/src/components/article_components/article_make_comment.css
frontend/my-app/src/components/article_components/article_make_comment.jsx
frontend/my-app/src/components/parity_components/tradingEqCommentCard.css
frontend/my-app/src/components/parity_components/tradingEqCommentCard.jsx
frontend/my-app/src/components/parity_components/tradingEqCommentHolder.css
frontend/my-app/src/components/parity_components/tradingEqCommentHolder.jsx
frontend/my-app/src/components/parity_components/tradingEqMakeComment.css
frontend/my-app/src/components/parity_components/tradingEqMakeComment.jsx
frontend/my-app/src/components/profile_components/othersArticles.jsx

Commenting on trading equipment works.

Feature f244

---

frontend/my-app/src/components/article_components/articleCommentCard.jsx
frontend/my-app/src/components/article_components/articleCommentHolder.jsx
frontend/my-app/src/components/article_components/articleDislike.jsx
frontend/my-app/src/components/article_components/articleLike.jsx
frontend/my-app/src/components/article_components/article_make_comment.jsx
frontend/my-app/src/components/article_components/wholeArticlePage.jsx
frontend/my-app/src/components/joint_components/commentDislike.jsx
frontend/my-app/src/components/joint_components/commentLike.jsx
frontend/my-app/src/components/nav_bars/traderNavbar.jsx
frontend/my-app/src/components/parity_components/tradingEqCommentCard.jsx
frontend/my-app/src/components/parity_components/tradingEqCommentHolder.jsx
frontend/my-app/src/components/parity_components/tradingEqMakeComment.jsx
frontend/my-app/src/components/profile_components/UnfullowButton.jsx

likes and dislikes for comments and articles
...
...

Feature f247

---

frontend/my-app/src/components/doVerify.jsx
frontend/my-app/src/components/verificationFailPage.jsx
frontend/my-app/src/containers/Login.jsx
frontend/my-app/src/containers/LoginRouter.jsx
frontend/my-app/src/home.jsx
frontend/my-app/src/index.css

Email verification is handled.

---

frontend/my-app/package-lock.json
frontend/my-app/package.json
frontend/my-app/src/components/article_components/articleCommentCard.jsx
frontend/my-app/src/components/article_components/articleDislike.jsx
frontend/my-app/src/components/article_components/articleLike.jsx
frontend/my-app/src/components/article_components/wholeArticlePage.jsx
frontend/my-app/src/components/joint_components/commentDislike.jsx
frontend/my-app/src/components/joint_components/commentLike.jsx
frontend/my-app/src/components/parity_components/tradingEqCommentCard.jsx
frontend/my-app/src/components/profile_components/FollowButton.jsx
frontend/my-app/src/index.js

Follow, like dislike button changes
...
...

Feature f252

---

frontend/my-app/package.json
frontend/my-app/public/index.html
frontend/my-app/src/containers/Signup.jsx
frontend/my-app/yarn.lock

Feature f288

---

frontend/my-app/src/containers/Signup.jsx

Feature f289

---

frontend/my-app/src/components/parity_components/graphPage.jsx
frontend/my-app/src/components/parity_components/navLinkComponents.jsx
frontend/my-app/src/components/parity_components/newParitiesPage.jsx
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/home.jsx

Parity Page improvement
...
...

improved parity page

---

frontend/my-app/package-lock.json
frontend/my-app/package.json
frontend/my-app/src/components/article_components/articleCommentHolder2.css
frontend/my-app/src/components/article_components/articleCommentHolder2.jsx
frontend/my-app/src/components/article_components/parity_make_comment.jsx
frontend/my-app/src/components/nav_bars/basicNavbar.jsx
frontend/my-app/src/components/parity_components/graph.jsx
frontend/my-app/src/components/parity_components/graphPage.css
frontend/my-app/src/components/parity_components/graphPage.jsx
frontend/my-app/src/components/parity_components/newParitiesPage.jsx
package-lock.json

Major update regarding parities, now page and comment works flawless
...
...

last changes for parities and some bug fixes

---

nova/nova/libs/parse_event_data.py

Fix time and country fields of the event API. See the issue for more details.
#286

Fix time and country fields of the event API

---

nova/nova/libs/parse_event_data.py

Reverts bounswe/bounswe2019group8#287

Revert "Fix time and country fields of the event API"

---

nova/README.md
nova/nova/av.py
nova/nova/models.py
nova/nova/other_views/events.py
nova/nova/other_views/parity_view.py
nova/nova/serializers.py
nova/nova/settings.py

CurrentPrice class is imported. Kronos is deleted from the project. Code is cleaned up.
See #269.

Import CurrentPrice and delete Kronos from project

---

mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Adapters/EventsAdapter.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/Entrance/BasicUserActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/Entrance/TraderUserActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/Entrance/VerificationActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/SearchDigitalActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/SearchForexActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/EventsFragment.kt
mobile/Mercatus/app/src/main/res/layout/activity_trader_user.xml
mobile/Mercatus/app/src/main/res/layout/activity_verification.xml
mobile/Mercatus/app/src/main/res/layout/event_layout.xml
mobile/Mercatus/app/src/main/res/values/strings.xml

Bug Events

---

frontend/my-app/src/components/parity_components/graphPage.jsx

page alignment

---

nova/nova/models.py
nova/nova/serializers.py

-Asset, Order, Notification models
-User fields: followed articles, followed equipments
...
...

Feature b270

---

nova/nova/models.py
nova/nova/other_views/order_view.py
nova/nova/serializers.py
nova/nova/signals.py

Added a signal receiver for orders. Whenever equipments are updated, this function can be triggered
to check the orders(BUY, SELL) related to the equipments updated.
Added Currency model for to be used in transactions
...
...

Feature b271

---

nova/nova/fixtures/commodities.json
nova/nova/fixtures/forexes.json
nova/nova/fixtures/indices.json

Add fixtures for commodities and forexes
See #303.

Add fixtures for commodities, forexes and indices

---

nova/nova/fixtures/digital_currencies.json
nova/nova/fixtures/etf.json
nova/nova/fixtures/stocks.json
nova/nova/models.py

Add fixtures for stocks, digital currencies and ETFs so that we can populate the database automatically after cleaning it
#305

Add fixtures for stocks, digital currencies and ETFs

---

nova/nova/models.py
nova/nova/serializers.py

Updates the models and serializers according to our new design.
#313

Feature f313

---

nova/nova/cron_jobs.py
nova/nova/fixtures/commodities.json
nova/nova/settings.py
nova/nova/urls.py

Added method for fetching current prices from NASDAQ is added. Also an endpoint for fetching all prices is added. Cron job key is required to use this endpoint.
See #308.

Implementing commodity prices fetcher

---

nova/nova/av.py
nova/nova/models.py

Refactored av.py, according to the new Price model
#315 
...

Feature b309

---

nova/nova/av.py
nova/nova/fixtures/stocks.json
nova/nova/nasdaq.py
nova/nova/other_views/parity_view.py
nova/nova/other_views/trading_eq_view.py

Implemented daily & intradaily stock price fetcher.
Updated av.
Equipments are now saved after updates.
#311 
...

Feature b311

---

nova/nova/nasdaq.py
nova/nova/urls.py

Added daily method for fetching commodity prices monthly. Also added method for deleting price objects that are not intraday and intraday prices that are older than yesterday.
#308

Add daily method for fetching commodity prices monthly

---

nova/nova/models.py
nova/nova/other_views/portfolio_view.py
nova/nova/serializers.py
nova/nova/urls.py

Added portfolio model, serializers, crud and portfolio follow operations.
Implemented necessary updates to other models.
#319 
You can find the documentation for Portfolio at [Mercatus API doc](https://documenter.getpostman.com/view/9777643/SWE9XbLG?version=latest)

Feature b319

---

nova/nova/models.py

- Asset amount does not have to be an integer
- Notification creation time should be named created_at
#328

fix Asset and Notification model bugs:

---

nova/nova/models.py
nova/nova/serializers.py
nova/nova/urls.py
nova/nova/utils/dicts.py
nova/nova/utils/validators.py
nova/nova/views/portfolios.py

Implements/updates the new portfolio endpoints according to our usual REST design.
#334

Feature b334

---

nova/nova/fixtures/groups.json
nova/nova/models.py
nova/nova/permissions.py
nova/nova/serializers.py
nova/nova/urls.py
nova/nova/views/assets.py

Implements endpoint for depositing cash from bank account to Mercatus account
#336 
See the update Postman documentation for example calls.
This PR also includes a feature that automatically adds USD asset of amount 0 to trader accounts. If you have some old user data, it might not work on them.

Cash Depositing

---

frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/components/profile_components/ProfileArea.css

Image uploading input is implemented.
...
...

Upload image feature

---

nova/nova/fixtures/forexes.json
nova/nova/fixtures/prices.json
nova/nova/serializers.py
nova/nova/urls.py
nova/nova/utils/numeric.py
nova/nova/views/assets.py

Feature b346

---

frontend/my-app/src/components/nav_bars/traderNavbar.jsx
frontend/my-app/src/components/portfolio_components/addTreqModal.css
frontend/my-app/src/components/portfolio_components/addTreqModal.jsx
frontend/my-app/src/components/portfolio_components/createPortfolio.jsx
frontend/my-app/src/components/portfolio_components/dropDownHandler.jsx
frontend/my-app/src/components/portfolio_components/followPortfolioButton.css
frontend/my-app/src/components/portfolio_components/followPortfolioButton.jsx
frontend/my-app/src/components/portfolio_components/followingPortfolioListHandler.jsx
frontend/my-app/src/components/portfolio_components/othersPortfolioHandler.jsx
frontend/my-app/src/components/portfolio_components/othersPortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/othersSinglePortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/ownPortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/portfolioListHandler.jsx
frontend/my-app/src/components/portfolio_components/removeTrEqButton.css
frontend/my-app/src/components/portfolio_components/removeTrEqButton.jsx
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.css
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.jsx
frontend/my-app/src/components/profile_components/FollowButton.jsx
frontend/my-app/src/components/profile_components/OthersProfileArea.jsx
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/home.jsx

Feature f325.2

---

frontend/my-app/src/components/nav_bars/basicNavbar.jsx
frontend/my-app/src/components/nav_bars/mainNavbar.jsx
frontend/my-app/src/components/nav_bars/traderNavbar.jsx
frontend/my-app/src/components/portfolio_components/createPortfolio.jsx
frontend/my-app/src/components/portfolio_components/ownPortfolioPage.jsx
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/components/profile_components/ProfilePage.jsx
frontend/my-app/src/home.jsx

Finished profile image update
Refreshed after portfolio creation
...
...
- [x ] Code runs

Feature f343

---

nova/nova/serializers.py

do not revert group to basic user when group is not specified in update

---

nova/nova/internal_views/nasdaq.py
nova/nova/urls.py
nova/nova/utils/functions.py
nova/nova/views/prices.py

Implemented daily, intradaily and current price endpoints.
#364

Implement views for prices

---

nova/nova/urls.py
nova/nova/views/recommendations.py

Implemented endpoint for recommending articles.
#366

Implement recommendation for articles

---

nova/nova/urls.py
nova/nova/views/recommendations.py

Implemented portfolio recommendations.
#370

Implement portfolio recommendations

---

nova/nova/signals.py
nova/nova/urls.py
nova/nova/views/notifications.py

Feature b368

---

frontend/my-app/package-lock.json
frontend/my-app/package.json
frontend/my-app/src/components/nav_bars/traderNavbar.jsx
frontend/my-app/src/components/notification_components/navbar_notif_icon.jsx
frontend/my-app/src/components/notification_components/notifListHandler.css
frontend/my-app/src/components/notification_components/notifListHandler.jsx
frontend/my-app/src/components/notification_components/notifModal.jsx
frontend/my-app/src/components/notification_components/notifPage.css
frontend/my-app/src/components/notification_components/notifPage.jsx
frontend/my-app/src/components/portfolio_components/addTreqModal.css
frontend/my-app/src/components/portfolio_components/createPortfolio.css
frontend/my-app/src/components/portfolio_components/createPortfolio.jsx
frontend/my-app/src/components/portfolio_components/followPortfolioButton.jsx
frontend/my-app/src/components/portfolio_components/ownPortfolioPage.css
frontend/my-app/src/components/portfolio_components/portfolioListHandler.jsx
frontend/my-app/src/components/portfolio_components/removeTrEqButton.css
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.css
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/components/profile_components/searchResults.jsx
frontend/my-app/src/components/profile_components/trEqSearchHandler.jsx
frontend/my-app/src/components/profile_components/userSearchHandler.jsx
frontend/my-app/src/home.jsx

Notifications are done.
Portfolios bugs are fixed.
User search handled.
Article and trader searches are to be handled.

Feature f369

---

nova/nova/settings.py
nova/nova/urls.py
nova/nova/views/semantic_search.py

Implemented semantic search for articles.
#373

Implement semantic search for articles

---

frontend/my-app/src/components/article_components/annotated_article.jsx
frontend/my-app/src/components/article_components/articleCommentCard.css
frontend/my-app/src/components/article_components/articleCommentHolder.jsx
frontend/my-app/src/components/article_components/main_article_holder.jsx
frontend/my-app/src/components/article_components/wholeArticlePage.css
frontend/my-app/src/components/article_components/wholeArticlePage.jsx
frontend/my-app/src/components/profile_components/OthersProfileArea.jsx

Added: Annotation maker, annotation parser, annotation viewer, annotation modals
Fixed issues of profile image of another user
Changed layout of whole article page
...
...

Annotation functionality, bugfixes

---

frontend/my-app/src/components/notification_components/notifListHandler.css
frontend/my-app/src/components/notification_components/notifListHandler.jsx
frontend/my-app/src/components/notification_components/notifPage.css
frontend/my-app/src/components/notification_components/notifPage.jsx

Fixes a little bug that prevents New Annotation text inside notifications.
Styles the notification table
...
...

Feature f371

---

frontend/my-app/src/components/profile_components/OthersProfileArea.jsx
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/components/profile_components/ProfileArea.css

Adds some nice styling to OwnProfile and OthersProfile
...
...

New styling for profile pages

---

frontend/my-app/src/components/article_components/writeArticlePage.css
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/components/profile_components/ProfileArea.css

A bulk update of Profile page styling, assets section, recommendations section(portfolio and articles),
invest (cash) function, new write article style
#381 
...

Feature f373

---

frontend/my-app/src/components/portfolio_components/addTreqModal.jsx
frontend/my-app/src/components/portfolio_components/createPortfolio.css
frontend/my-app/src/components/portfolio_components/followPortfolioButton.jsx
frontend/my-app/src/components/portfolio_components/othersPortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/othersSinglePortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/ownPortfolioPage.css
frontend/my-app/src/components/portfolio_components/ownPortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/removeTrEqButton.css
frontend/my-app/src/components/portfolio_components/removeTrEqButton.jsx
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.css
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.jsx

Applies styling to portfolio components.
...
...

Portfolio components style

---

mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/EventsFragment.kt

1. Next 3 days items are listed in the events list 
1. All events are sorted according to their importance
#321

m321_Updates_on_events

---

frontend/my-app/src/components/portfolio_components/followPortfolioButton.jsx
frontend/my-app/src/components/portfolio_components/othersSinglePortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.css
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.jsx

Adds new styles for portfolio page.
...
...

New look for portfolio page

---

frontend/my-app/src/components/event_components/eventCard.jsx
frontend/my-app/src/components/profile_components/OthersProfileArea.jsx
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/home.jsx

Feature f998

---

frontend/my-app/src/components/portfolio_components/addTreqModal.jsx

Added icon for new equipment button

---

frontend/my-app/src/components/portfolio_components/followingPortfolioListHandler.jsx
frontend/my-app/src/components/portfolio_components/othersSinglePortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.css
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.jsx
frontend/my-app/src/components/profile_components/eventSemanticHandler.jsx
frontend/my-app/src/components/profile_components/searchResults.jsx
frontend/my-app/src/home.jsx

Feature f387

---

mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/MainActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/AddCashBody.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/AssetEquipmentModel.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/BuyAssetsModel.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/GetAssetsBody.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/ArticlesFragment.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/AssetsFragment.kt
mobile/Mercatus/app/src/main/res/layout/fragment_asset.xml
mobile/Mercatus/app/src/main/res/menu/activity_main_drawer.xml
mobile/Mercatus/app/src/main/res/navigation/mobile_navigation.xml
mobile/Mercatus/app/src/main/res/values/strings.xml

1. Create Asset Fragment and link with the backend
1. Get assets
1. Add cash
#394

Add cash and create assets

---

frontend/my-app/src/components/nav_bars/basicNavbar.jsx
frontend/my-app/src/components/nav_bars/traderNavbar.jsx
frontend/my-app/src/components/parity_components/downvote.jsx
frontend/my-app/src/components/parity_components/graph.jsx
frontend/my-app/src/components/parity_components/graphPage.jsx
frontend/my-app/src/components/parity_components/newParitiesPage.jsx
frontend/my-app/src/components/parity_components/upvote.jsx
frontend/my-app/src/components/parity_components/voteholder.jsx
frontend/my-app/src/components/portfolio_components/othersSinglePortfolioPage.jsx
frontend/my-app/src/components/portfolio_components/singleOwnPortfolioPage.jsx
frontend/my-app/src/components/profile_components/trEqSearchHandler.jsx
frontend/my-app/src/home.jsx

Change treq page so that routing to page from different links is possible.
Implemented the upvote and downvote to each parity.
Corrected buy/sell functionalities.
Created icon links from portfolios to corresponding parities.
...
...

Feature f1000

---

frontend/my-app/src/components/article_components/articleCommentCard.css
frontend/my-app/src/components/article_components/articleCommentHolder2.jsx
frontend/my-app/src/components/parity_components/graph.jsx
frontend/my-app/src/components/parity_components/graphPage.jsx
frontend/my-app/src/components/parity_components/newParitiesPage.jsx
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx

Fixed asset display in profile page
Added response modals to the transactions
Changed style of the equipments page
Changed style of the comment boxes
...
...

Feature f final1

---

frontend/my-app/src/components/notification_components/notifListHandler.jsx
frontend/my-app/src/components/profile_components/OwnProfileArea.jsx
frontend/my-app/src/components/profile_components/annotationSemanticHandler.jsx
frontend/my-app/src/components/profile_components/anySearchHandler.css
frontend/my-app/src/components/profile_components/articleSemanticHandler.jsx
frontend/my-app/src/components/profile_components/assetButtonHandler.css
frontend/my-app/src/components/profile_components/assetButtonHandler.jsx
frontend/my-app/src/components/profile_components/commentSemanticHandler.jsx
frontend/my-app/src/components/profile_components/eventSemanticHandler.jsx
frontend/my-app/src/components/profile_components/searchResults.css
frontend/my-app/src/components/profile_components/searchResults.jsx
frontend/my-app/src/components/profile_components/trEqSearchHandler.jsx
frontend/my-app/src/components/profile_components/userSearchHandler.jsx

Feature f405

---

mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Adapters/AssetsAdapter.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/CreateAssetsActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/AssetsFragment.kt
mobile/Mercatus/app/src/main/res/layout/asset_layout.xml
mobile/Mercatus/app/src/main/res/layout/fragment_asset2.xml

1. Sell Asset
1. Buy Asset
#401

Buy and Sell Assets

---

frontend/my-app/src/components/nav_bars/traderNavbar.jsx
frontend/my-app/src/components/parity_components/graph.jsx
frontend/my-app/src/components/parity_components/graphPage.css
frontend/my-app/src/components/parity_components/graphPage.jsx
frontend/my-app/src/components/parity_components/newParitiesPage.jsx
frontend/my-app/src/home.jsx

Feature f990

---

mobile/Mercatus/app/src/main/AndroidManifest.xml
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Adapters/EquipmentAdapter.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Adapters/PortfoliosAdapter.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/CreateAssetsActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/Portfolios/ShowPortfolioActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/GetPortfolioBody.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UpdatePortfolio.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/AssetsFragment.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/PortfolioFragment.kt
mobile/Mercatus/app/src/main/res/layout/activity_show_portfolio.xml
mobile/Mercatus/app/src/main/res/layout/equipment_item_layout.xml
mobile/Mercatus/app/src/main/res/layout/fragment_asset.xml

1. Create a different page for current assets and order
1. Buy Asset
1. Sell Asset
1. Buy Cash

Buy Cash and Assets

---

mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/API/RetrofitClient.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Adapters/EquipmentAdapter.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Adapters/PortfoliosAdapter.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Fragments/Portfolios/ShowPortfolioActivity.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/GetPortfolioBody.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/GetSpecificPortfolio.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/PortfolioShowBody.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/Models/UpdatePortfolio.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/ForexFragment.kt
mobile/Mercatus/app/src/main/java/com/bounswe/mercatus/ui/PortfolioFragment.kt
mobile/Mercatus/app/src/main/res/drawable/ic_security_black_24dp.xml
mobile/Mercatus/app/src/main/res/layout/activity_show_portfolio.xml
mobile/Mercatus/app/src/main/res/layout/fragment_portfolios.xml
mobile/Mercatus/app/src/main/res/layout/item_eqp.xml
mobile/Mercatus/app/src/main/res/layout/portfolio_layout.xml

Portfolio Improvement and Bugs fixed
#416

Portfolio Improvement and Bugs fixed
